### ISSUE TITLE
Shut be updated!?

### ISSUE THREAD

**Issue by Binifada1956** [Limych/ha-average#166] opened 2022-10-13 14:26 UTC
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77 
First occurred: 16:15:38 (1 occurrences) 
Last logged: 16:15:38

Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for average using this method at custom_components/average/sensor.py, line 258: temperature = convert_temperature(float(temperature), entity_unit, ha_unit)

**Comment by lmagyar** [comment] 2022-10-14 21:57
Seems to be a duplicate of #161, that is repaired though not published yet.

**Comment by lmagyar** [comment] 2023-03-02 16:06
A new version should be released, because the end date (Apr. of 2023) for this integration is nearer and nearer.

It still causes warnings:
```
2023-03-02 16:59:21.289 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for average using this method at custom_components/average/sensor.py, line 258: temperature = convert_temperature(float(temperature), entity_unit, ha_unit)
```

**Comment by lmagyar** [comment] 2023-03-06 11:01
I've added a comment in the forums on how to replace it with the built in integrations, see: https://community.home-assistant.io/t/average-sensor/111674/154

This integration seems to be abandoned, I've initiated to remove it from the store, see: https://github.com/hacs/integration/issues/3083

**Comment by gieljnssns** [comment] 2023-08-07 01:50
https://github.com/Limych/ha-average/issues/189#issuecomment-1667063670

**Closed as completed** 2023-10-01 11:12 UTC
Labels: bug
